<a href="https://colab.research.google.com/github/Cheunji/aipython/blob/main/24_01_09(numpy).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# 1부터 10까지(미포함)의 2걸음 크기의 정수값 배열 생성
# arange(Start, Stop, Step)
arr = np.arange(1, 10, 2)
print(arr)

# 모양이 (3, 4)인 모든 값이 1인 배열 생성
# ones(shape)
ones_2d = np.ones((3,4))
print(ones_2d)

# 0과 1사이를 10등분하고자 할 때 등분값 배열 생성
# linspace(Start, Stop, Num)
arr1 = np.linspace(0, 1, 10)
print(arr1)

[1 3 5 7 9]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
A = np.arange(1,26).reshape(5,5)
print(A)
print(A.shape)
print(A[3,3])
print(A[:2, :2])
print(A[3:,3:])
print(A[:2, ])
print(A[: ,-2:])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)
19
[[1 2]
 [6 7]]
[[19 20]
 [24 25]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 4  5]
 [ 9 10]
 [14 15]
 [19 20]
 [24 25]]


In [19]:
arr = np.arange(1,37).reshape(6,6)
print(arr)

print(arr.shape, arr.size)

arr1 = arr.reshape(3,4,3)
print(arr1)

arr2 = arr.reshape(36)
print(arr2)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
(6, 6) 36
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]
  [19 20 21]
  [22 23 24]]

 [[25 26 27]
  [28 29 30]
  [31 32 33]
  [34 35 36]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36]
